name: Merge

on:
  pull_request:
  merge_group:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: list
        run: ls -Alf
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: git log
        run: git log --graph --pretty=tformat:'%Cred%h%Creset %Cblue%G?%Creset -%C(auto)%d%Creset %s %Cgreen(%an %ar)%Creset' --branches --remotes
      - name: display
        run: |
            echo "base_sha: ${{ github.event.merge_group.base_sha }}"
            echo "base_ref: ${{ github.event.merge_group.base_ref }}"
            echo "head_sha: ${{ github.event.merge_group.head_sha }}"
            echo "head_ref: ${{ github.event.merge_group.head_ref }}"
      - name: git diff
        run: git diff ${{ github.event.merge_group.base_sha }}...${{ github.event.merge_group.head_sha }}
